Remove-Module AzureVMSSLBUpgradeModule -force
Import-Module AzureVMSSLBUpgradeModule.psd1 -Force
AzureVMSSLBUpgrade -ResourceGroupName basiclb -BasicLoadBalancerName basiclb-loadbalancer -StdLoadBalancerName stdlb-loadbalancer