name: Publisher

on:
  release:
    types: [published]

env:
  gallerykey: ${{ secrets.POWERSHELLGALLERY }}
  modulepath: "AzureBasicLoadBalancerUpgrade"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      #Get the code files from the repo
      - uses: actions/checkout@v3

      #get list of files changed in PR
      - id: files
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true
        with:
          format: json

      # Runs a set of commands using the runners shell
      - name: Increment changed module versions
        id: module_versions
        run: |
          # Automatically increment the 'build' version numbers on a PS module file
          
          $files = '${{ steps.files.outputs.modified }}' | ConvertFrom-Json
          
          $moduleVersionRegex = [regex]"(?:ModuleVersion\s?=\s?')([\d\.]*)'" 

          $moduleChangedFileList = $files | where-object { $_ -match '\.psm1$'}

          ForEach ($moduleChangedFile in $moduleChangedFileList) {

              try {
                $moduleManifestPath = Get-Item -Path ($moduleChangedFile -replace '\.psm1$','.psd1') -ErrorAction Stop
              }
              catch {
                Write-Error "Error locating .psd1 file for module '$moduleChangedFile'. This file should reside in the same directory as the psm1."
              }
              
              $moduleManifest = Get-Item $moduleManifestPath
              $content = Get-Content $moduleManifest

              If ($moduleVersionMatches = $moduleVersionRegex.matches($content)) {
                  If ($moduleVersionMatches.count -eq 1) {
                      $moduleVersionLine = $moduleVersionMatches[0].Groups[0].Value
                      $currentModuleVersion = $moduleVersionMatches[0].Groups[1].Value

                      If ($version = $currentModuleVersion -as [version]) {
                          $major = $version.Major
                          $minor = $version.Minor
                          $build = $version.Build + 1 # add 1 to current version build number

                          $newVersion = [version]::new($major,$minor,$build)
                      }
                      Else {
                          Write-Error "Version string '$currentModuleVersion' cannot be converted to type [Version]. File: '$moduleManifest'"
                      }

                      $newVersionLine = $moduleVersionLine -replace $currentModuleVersion,$newVersion

                      $moduleManifest | Set-Content -Value ($content -replace $moduleVersionLine,$newVersionLine)
                  }
                  Else {
                      Write-Error "More than one matches for regex '$moduleVersionRegex' found in file '$moduleManifest'"
                  }
              }
          }

          # output whether modules were changed
          If ($moduleChangedFileList.count -eq 0) {
            Write-Host "::set-output name=versions_changed::$($false)"
          }
          Else {
             Write-Host "::set-output name=versions_changed::$($true)"
          }
        shell: pwsh
      
      #commit updated module versions
      - name: Commit and Push Module Version Updates
        uses: actions-x/commit@v6
        if: steps.module_versions.outputs.versions_changed == 'true'
        with:
          message: GH Workflow - increment module versions

      # Publish the module to the PowerShell Gallery
      - name: PowerShell Gallery Publisher
        shell: pwsh
        run: |
          Write-Output "Checking module folder exists"
          if(Test-Path "${{ env.modulepath }}"){
            Write-Output "Module folder: ${{ env.modulepath }} exists"
            Write-Output "Publishing module to PowerShell Gallery"
            try{
              Publish-Module -Path ${{ env.modulepath }} -NuGetApiKey "${{ env.gallerykey }}"
            }
            catch{
              Write-Output "Error publishing module to PowerShell Gallery"
              Write-Output $_
            }
          }
          else{
            Write-Output "Module folder: ${{ env.modulepath }} does not exist"
            exit 1
          }